import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import {GetStaticProps, NextPage} from "next";
import imageLoader from "../../imageLoader";
import {Datum, GetBossResults} from "../../types";

const inter = Inter({ subsets: ['latin'] })

const Home: NextPage<{ bosses: Datum[] }> = ({bosses}) => {
  return (
    <div className={styles.main}>
      <Head>
        <title>Elden Ring Database</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* DB_CONNECT: {process.env.NEXT_PUBLIC_DB_CONNECT}*/}
        <hr />
        {bosses.map((boss) => {
            return <div key={boss.id}>
                <Link href={`/bosses/${boss.id}`} target={"_blank"}>
                <h3>
                    {boss.name}
                </h3>
                <Image
                    loader={imageLoader}
                    unoptimized
                    src={boss.image || "{}"}
                    alt={boss.name}
                    width={"200"}
                    height={"200"}
                />
            </Link>
            </div>
        })}
      </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
    const res = await fetch("https://eldenring.fanapis.com/api/bosses?limit=238")
    const {data}: GetBossResults = await res.json();

    return {
        props: {
            bosses: data,
        },
    }
}

export default Home;
